### ISSUE TITLE
Playbook fails on Groovy and Bionic default server 

### ISSUE THREAD

**Issue by evillogic** [julianoborba/Ansible-Cuckoo#10]
Hey! Thanks for the awesome work.

This playbook doesn't work out of the box for Ubuntu 20 or 18.

Bionic is easier to fix as it requires you to install python2 from apt, then pip from an install script. Afterwards you still need to add the i386 arch before many of the libraries will pull down from apt.

Groovy appears to be more difficult, but I didn't spend a ton of time on it. It would be cool if we could use it though.

Artful doesn't appear to work because it's not an LTS release.

The build then fails when installing mitmproxy, presumably because everything is in python2. Stopping here for now. 
Is this project still maintained?

**Comment by julianoborba** [comment]
Hello! Thank you and thank you for reaching me out to point your needs!

The project has stopped, it was a part of set of other initiatives that also stopped.
I'm unable to keep the project at this time, yet I'm refusing to archive it since I have a desire to keep it in a future (sorry).

Said that, it runs for Ubuntu 16.04 Desktop (amd64) and Ubuntu 17.10 Minimal (amd64) - I know, it is outdated, but...

Looks like we have another generous buddy (https://github.com/abzzzzzzzz) keeping it up and helping our awesome community, so take a look, maybe is what you need: https://github.com/abzzzzzzzz/Ansible-Cuckoo. [See the changes](https://github.com/abzzzzzzzz/Ansible-Cuckoo/commit/87cd82ea168d40463d392bd71ac94d65b81f24e1).

I'm very glad to see my work spreading new seeds of prosperity for those seeking for that resource.

Sorry for the delayed answer. If possible share your considerations about the alternative you found for your need, that way we can close this issue with at least some new available resource.

Best regards!
